add-marks
AlSl94/java-filmorate pull request #40
Opened 2022-08-25 20:01 UTC by AlSl94

Добавили новый контроллер Marks
Переписали методы
Добавили тестирование методов
Пока еще не удалили старый функционал с лайками, сделаем это немного попозже
Исправил main, чтобы изменения были более очевидны

2022-08-26 05:21 UTC, svstudy-yandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/MarkController.java
> +        consumes = MediaType.ALL_VALUE,
Молодцы, что используете готовые константы!

2022-08-26 06:29 UTC, svstudy-yandex requested changes
В целом ок, но есть одна недоработка (это критикал) и некоторые пожелания/замечания

2022-08-26 06:29 UTC, svstudy-yandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        final String sqlQuery = "SELECT f.FILM_ID, f.NAME, f.DESCRIPTION, f.MPA_ID, mr.MPA as MPA, " +
Мне кажется красивее будет селектить count и считывать как
jdbcTemplate.queryForObject(sqlQuery, Integer.class, id);
Потом соответственно проверять на 0. Вместо того, чтобы ловить exception

2022-08-26 06:29 UTC, svstudy-yandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/MarkController.java
> +    @GetMapping(value = "/score/best")
А задачу add-most-populars вы не делали? По идее это как раз оно и можно было бы использовать названия ендпоинтов оттуда (/films/popular)

2022-08-26 06:29 UTC, svstudy-yandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/mark/MarkDbStorage.java
> +//    public Collection<Film> getFilmsWithHigherMarkAsTarget(double targetMark) {
Закомменированный код лучше удалить

2022-08-26 06:29 UTC, svstudy-yandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/mark/MarkDbStorage.java
> +    public Double averageFilmRating(Long filmId) {
Кажется метод не используется (кроме тестов)

2022-08-26 06:29 UTC, svstudy-yandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
>      public void checkUserExistence(Long id) {
Аналогично как и в checkFilmExistence

2022-08-26 06:29 UTC, svstudy-yandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
>          final String sqlQuery = "SELECT user_id, email, login, name, birthday FROM users WHERE user_id = ?";
По идее тут можно просто переиспользовать (вызвав 2 раза) метод checkUserExistence(Long id)

2022-08-26 06:29 UTC, svstudy-yandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        Double mark = resultSet.getDouble("mark");
Если тип столбца mark - это smallint, то почему тип переменной (тут и по цепочке выше) - double?

2022-08-26 06:29 UTC, svstudy-yandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        List<Long> recommendation = FilmRecommendation.getRecommendation(targetUserRates, similarUsersRates);
Кажется в алгоритме рекомендаций забыли реализовать требование из задания - "А рекомендовать только с положительной оценкой."

2022-08-26 14:24 UTC, Sergej-Nishpal commented on src/main/java/ru/yandex/practicum/filmorate/service/MarkService.java
> +@Validated
Аннотацию убрали.

2022-08-26 14:46 UTC, Sergej-Nishpal commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        final String sqlQuery = "SELECT f.FILM_ID, f.NAME, f.DESCRIPTION, f.MPA_ID, mr.MPA as MPA, " +
Метод исправили.

2022-08-26 14:54 UTC, Sergej-Nishpal commented on src/main/java/ru/yandex/practicum/filmorate/controllers/MarkController.java
> +    @GetMapping(value = "/score/best")
Перенесли эндпойнт в FilmController, назвали, как было раньше - /films/popular

2022-08-26 14:57 UTC, Sergej-Nishpal commented on src/main/java/ru/yandex/practicum/filmorate/storage/mark/MarkDbStorage.java
> +//    public Collection<Film> getFilmsWithHigherMarkAsTarget(double targetMark) {
Это наша заготовка на будущее, убрали.

2022-08-26 15:03 UTC, Sergej-Nishpal commented on src/main/java/ru/yandex/practicum/filmorate/storage/mark/MarkDbStorage.java
> +    public Double averageFilmRating(Long filmId) {
Пока использовался только в тестах. Убрали.

2022-08-26 15:08 UTC, Sergej-Nishpal commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
>      public void checkUserExistence(Long id) {
Метод исправили.

2022-08-26 15:11 UTC, Sergej-Nishpal commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
>          final String sqlQuery = "SELECT user_id, email, login, name, birthday FROM users WHERE user_id = ?";
Исправили метод, переиспользуем checkUserExistence(Long id).

2022-08-26 16:41 UTC, Sergej-Nishpal commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        Double mark = resultSet.getDouble("mark");
Тип переменной изменили на Integer, в т.ч. по цепочке выше.

2022-08-26 16:55 UTC, Sergej-Nishpal commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        List<Long> recommendation = FilmRecommendation.getRecommendation(targetUserRates, similarUsersRates);
К сожалению, забыли. Исправили этот момент.

2022-08-26 18:26 UTC, Sergej-Nishpal commented on src/main/java/ru/yandex/practicum/filmorate/controllers/MarkController.java
> +    @GetMapping(value = "/score/best")
Дополнительно перенесли - теперь в LikeController, т.к. этот эндпойнт был там.

2022-08-26 18:27 UTC, Sergej-Nishpal commented on src/main/java/ru/yandex/practicum/filmorate/storage/mark/MarkDbStorage.java
> +    public Double averageFilmRating(Long filmId) {
Теперь снова вернули, но в другой класс. Метод понадобился в связи с остальными замечаниями.

2022-08-26 18:28 UTC, Sergej-Nishpal commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        List<Long> recommendation = FilmRecommendation.getRecommendation(targetUserRates, similarUsersRates);
Дальше пришлось внести дополнительные изменения.

2022-08-27 13:44 UTC, svstudy-yandex commented
Кажется всё ок! Молодцы)

2022-08-27 13:46 UTC, merged