add-average-rating
AlSl94/java-filmorate pull request #44
Opened 2022-08-27 19:05 UTC by AlSl94

Добавили поле со средним рейтингом фильмам, а так же сделали рефактор метода SlopeOne, сделав его более универсальным

2022-08-27 19:37 UTC, svstudy-yandex commented
Сейчас вы вычисляете средний рейтинг фильма при каждом чтении фильма/фильмов из базы. Т.к чтение фильмов это самая нагруженная операция в этом приложении, то это может работать медленно. 
Другой варинат - добавить поле рейтинга в таблицу фильмов и обновлять его при изменении оценки этого фильма пользователями.

2022-08-28 07:55 UTC, svstudy-yandex requested changes
Забыли удалить join с таблицей оценок

2022-08-28 07:55 UTC, svstudy-yandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
>                  "LEFT JOIN MARKS M on f.FILM_ID = M.FILM_ID " +
Теперь этот join тут лишний. И в других местах тоже надо пройтись убрать, где он не нужен

2022-08-28 07:55 UTC, svstudy-yandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/mark/MarkDbStorage.java
> +        final String sqlUpdateQuery = "UPDATE FILMS " +
Проверяли, что будет в колонке, если еще ни одной оценки нет?

2022-08-28 08:25 UTC, AlSl94 commented on src/main/java/ru/yandex/practicum/filmorate/storage/mark/MarkDbStorage.java
> +        final String sqlUpdateQuery = "UPDATE FILMS " +
Проверяли, в поле будет null, а в постман передается 0.0

2022-08-28 08:25 UTC, AlSl94 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
>                  "LEFT JOIN MARKS M on f.FILM_ID = M.FILM_ID " +
Все исправлено, все работает! :)

2022-08-28 08:34 UTC, svstudy-yandex approved these changes
Отлично!

2022-08-28 08:42 UTC, merged